version: '3.5'

networks:
  port-ability-proxy:
    external: true
  internal:
    external: false

services:

  portainer:
    image: portainer/portainer
    container_name: "portainer_portainer"
    command: ${AUTH} -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
      - port-ability-proxy
    labels:
      - traefik.backend=portainer_portainer
      - traefik.port=9000
      - traefik.frontend.rule=Host:${PROJECT_FULL_URL}
      - traefik.docker.network=port-ability-proxy
